kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  selector:
    name: locust
    role: master
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
        - name: locust
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: LOCUST_MODE
              key: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              key: TARGET_HOST
              value: {{.Values.targetUrl}}
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
